server:
  port: 8083

spring:
  application:
    name: trip

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: trip-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
      # Recommended property for JSON Deserialization when using Protobuf
      properties:
        spring.json.use.type.headers: false
        # Idempotent Consumer Setting
        isolation.level: read_committed   # Ensures consumer reads only committed messages

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      # Idempotent Producer Settings
      properties:
        enable.idempotence: true
        acks: all
        retries: 2147483647               # Integer.MAX_VALUE
        max.in.flight.requests.per.connection: 1

  data:
    redis:
      host: redis
      port: 6379

grpc:
  server:
    port: 9094

kafka:
  topics:
    rider-ride-completion: "rider-ride-completion"
    driver-ride-completion: "driver-ride-completion"
    driver-location-rider: "driver-location-rider"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://registry:8761/eureka}

  instance:
    prefer-ip-address: true
    metadata-map:
      grpc.port: 9094

logstash:
  host: logstash
  port: 5044