spring:
  application:
    name: trip
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ByteArrayDeserializer
      group-id: trip-service
      # Recommended property for JSON Deserialization when using Protobuf
      properties:
        spring.json.use.type.headers: false
    listener:
      ack-mode: manual
  data:
    redis:
      host: redis # We have assumed that "redis" is a Docker container. We will need to use Docker volumes to make the cache persistent.
      port: 6379
