apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
  namespace: metro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          # image: driver-driver-service:latest
          # imagePullPolicy: IfNotPresent
          image: inevertheless/driver_microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
            - containerPort: 9090
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "metro-kafka-kafka-bootstrap:9092"
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: "metro-kafka-kafka-bootstrap:9092"
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: "metro-kafka-kafka-bootstrap:9092"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://registry:8761/eureka"
            - name: LOGSTASH_HOST
              value: "logstash"
            - name: LOGSTASH_PORT
              value: "5044"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: metro
spec:
  selector:
    app: driver-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8081
      name: http
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc # Assuming 9090 is for gRPC or similar
  type: ClusterIP
