version: "3.8"

services:
  trip-service:
    build:
      context: ..
      dockerfile: trip/Dockerfile
    container_name: trip-service
    ports:
      - "8087:8083"
      - "9094:9094"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_URL: http://registry:8761/eureka
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5044
    networks:
      - infra_default

networks:
  infra_default:
    external: true
