apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: metro
spec:
  selector:
    app: logstash
  ports:
    - name: tcp-logs
      port: 5044
      targetPort: 5044
      protocol: TCP
