spring:
  application:
    name: rider
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: rider-service
      # Recommended property for JSON Deserialization when using Protobuf
      properties:
        spring.json.use.type.headers: false
    listener:
      ack-mode: manual
  data:
    redis:
      host: redis
      port: 6379
  grpc:
    server:
      port: 9090

kafka:
  topics:
    rider-requests: "rider-requests"

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true          # ✅ Register this service with Eureka
    fetch-registry: true                # ✅ Allow discovery of other services
    service-url:
      defaultZone: ${EUREKA_URL:http://registry:8761/eureka}
  instance:
    prefer-ip-address: true             # ✅ Use IP instead of hostname
    metadata-map:
      grpc.port: 9093                   # ✅ Advertise gRPC port to Eureka
logstash:
  host: localhost
  port: 5044