server:
  port: 8084   # Use a unique port for the matching HTTP service

spring:
  application:
    name: matching

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: matching-service
      properties:
        spring.json.use.type.headers: false

    listener:
      ack-mode: manual

  data:
    redis:
      host: redis
      port: 6379

grpc:
  server:
    port: 9091

kafka:
  topics:
    rider-driver-match: rider-driver-match

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://registry:8761/eureka}

  instance:
    prefer-ip-address: true
    metadata-map:
      grpc.port: 9091

logstash:
  host: logstash
  port: 5044
