spring:
  application:
    name: matching
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ByteArrayDeserializer
      group-id: matching-service
      # Recommended property for JSON Deserialization when using Protobuf
      properties:
        spring.json.use.type.headers: false
    listener:
      ack-mode: manual
  data:
    redis:
      host: redis
      port: 6379
  grpc:
    server:
      port: 9090

kafka:
  topics:
    rider-driver-match: "rider-driver-match"

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true          # ✅ Register this matching service with Eureka
    fetch-registry: true                # ✅ Enable discovery of other services
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true             # ✅ Use IP address for registration
    metadata-map:
      grpc.port: 9091                   # ✅ Advertise gRPC port for service discovery
logstash:
  host: logstash
  port: 5044