apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-metro-cluster
  namespace: metro
  labels:
    team: metro
spec:
  teamId: "metro"
  volume:
    size: 5Gi
  numberOfInstances: 2
  users:
    metrouser:  # username
    - superuser
    - createdb
  databases:
    metrocarpool: metrouser  # dbname: owner
  postgresql:
    version: "16"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
