apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: metro-db
  namespace: metro
spec:
  teamId: "metro"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    metro_user:  # logical user associated with the DB
    - superuser
    - createdb
  databases:
    metrocarpool: metro_user  # dbname: owner
  postgresql:
    version: "16"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
