version: "3.8"

services:
  driver-service:
    build:
      context: ..
      dockerfile: driver/Dockerfile
    container_name: driver-service
    ports:
      - "8085:8081"
      - "9090:9090"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5044

    # Link to infrastructure network
    networks:
      - infra_default

networks:
  infra_default:
    external: true
