apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: metro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
            - containerPort: 9095
          env:
            # App identity
            - name: SPRING_APPLICATION_NAME
              value: user

            # Postgres connection
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/metrocarpool
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres

            # Eureka
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://registry:8761/eureka

            # Logging
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: "5044"
