spring:
  application:
    name: driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ByteArrayDeserializer
      group-id: driver-service
      # Recommended property for JSON Deserialization when using Protobuf
      properties:
        spring.json.use.type.headers: false
    listener:
      ack-mode: manual
  data:
    redis:
      host: redis
      port: 6379
  grpc:
    server:
      port: 9090
kafka:
  topics:
    driver-location-topic: "driver-updates"
    ride-completion-topic: "trip-completed"
#server:
#  port: 8081
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka