spring:
  application:
    name: driver
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      # Idempotent Producer Settings
      properties:
        enable.idempotence: true
        acks: all
        retries: 2147483647               # Integer.MAX_VALUE
        max.in.flight.requests.per.connection: 1
    consumer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: driver-service
      # Recommended property for JSON Deserialization when using Protobuf
      properties:
        spring.json.use.type.headers: false
        # Idempotent Consumer Setting
        isolation.level: read_committed   # Ensures consumer reads only committed messages
    listener:
      ack-mode: manual
  data:
    redis:
      host: redis
      port: 6379
  grpc:
    server:
      port: 9090
  cloud:
    compatibility-verifier:
      enabled: false

kafka:
  topics:
    driver-location-topic: "driver-updates"
    ride-completion-topic: "trip-completed"

#server:
#  port: 8081

eureka:
  client:
    register-with-eureka: true          # ✅ Register this driver service with Eureka
    fetch-registry: true                # ✅ Allow this service to discover others if needed
    service-url:
      defaultZone: http://registry:8761/eureka
  instance:
    prefer-ip-address: true             # ✅ Use IP address when registering with Eureka
    metadata-map:
      grpc.port: 9090                   # ✅ gRPC port metadata for other services to discover
logstash:
  host: logstash
  port: 5044